# -*- coding: utf-8 -*-
"""
item class to store scrapped information from reuters financial page
"""
import scrapy


class ReutersItem(scrapy.Item):
    """
    column names for scrapped information
    """
    response_status = scrapy.Field()
    response_url = scrapy.Field()
    symbol = scrapy.Field()
    date_scrapped = scrapy.Field()
    company_name = scrapy.Field()
    wrong_symbol = scrapy.Field()
    No_consensus_analysis_data_available = scrapy.Field()

    sales_consensus_box1 = scrapy.Field()
    sales_consensus_box2 = scrapy.Field()
    sales_consensus_box3 = scrapy.Field()
    sales_consensus_box4 = scrapy.Field()
    earning_consensus_box1 = scrapy.Field()
    earning_consensus_box2 = scrapy.Field()
    earning_consensus_box3 = scrapy.Field()
    earning_consensus_box4 = scrapy.Field()
    earning_consensus_box5 = scrapy.Field()

    sales_estimates_box1 = scrapy.Field()
    sales_estimates_box2 = scrapy.Field()
    sales_estimates_box3 = scrapy.Field()
    sales_estimates_box4 = scrapy.Field()
    earning_estimates_box1 = scrapy.Field()
    earning_estimates_box2 = scrapy.Field()
    earning_estimates_box3 = scrapy.Field()
    earning_estimates_box4 = scrapy.Field()
    earning_estimates_box5 = scrapy.Field()

    sales_mean_box1 = scrapy.Field()
    sales_mean_box2 = scrapy.Field()
    sales_mean_box3 = scrapy.Field()
    sales_mean_box4 = scrapy.Field()
    earning_mean_box1 = scrapy.Field()
    earning_mean_box2 = scrapy.Field()
    earning_mean_box3 = scrapy.Field()
    earning_mean_box4 = scrapy.Field()
    earning_mean_box5 = scrapy.Field()

    sales_high_box1 = scrapy.Field()
    sales_high_box2 = scrapy.Field()
    sales_high_box3 = scrapy.Field()
    sales_high_box4 = scrapy.Field()
    earning_high_box1 = scrapy.Field()
    earning_high_box2 = scrapy.Field()
    earning_high_box3 = scrapy.Field()
    earning_high_box4 = scrapy.Field()
    earning_high_box5 = scrapy.Field()

    sales_low_box1 = scrapy.Field()
    sales_low_box2 = scrapy.Field()
    sales_low_box3 = scrapy.Field()
    sales_low_box4 = scrapy.Field()
    earning_low_box1 = scrapy.Field()
    earning_low_box2 = scrapy.Field()
    earning_low_box3 = scrapy.Field()
    earning_low_box4 = scrapy.Field()
    earning_low_box5 = scrapy.Field()

    sales_year_ago_box1 = scrapy.Field()
    sales_year_ago_box2 = scrapy.Field()
    sales_year_ago_box3 = scrapy.Field()
    sales_year_ago_box4 = scrapy.Field()
    earning_year_ago_box1 = scrapy.Field()
    earning_year_ago_box2 = scrapy.Field()
    earning_year_ago_box3 = scrapy.Field()
    earning_year_ago_box4 = scrapy.Field()
    earning_year_ago_box5 = scrapy.Field()

    revenue = scrapy.Field()
    earnings_per_share = scrapy.Field()

    P_E_Ratio_TTM_Company = scrapy.Field()
    P_E_High_Company = scrapy.Field()
    P_E_Low_Company = scrapy.Field()
    Beta_Company = scrapy.Field()
    Price_to_Sales_TTM_Company = scrapy.Field()
    Price_to_Book_MRQ_Company = scrapy.Field()
    Price_to_Tangible_Book_MRQ_Company = scrapy.Field()
    Price_to_Cash_Flow_TTM_Company = scrapy.Field()
    Owned_Institutions_Company = scrapy.Field()

    P_E_Ratio_TTM_industry = scrapy.Field()
    P_E_High_industry = scrapy.Field()
    P_E_Low_industry = scrapy.Field()
    Beta_industry = scrapy.Field()
    Price_to_Sales_TTM_industry = scrapy.Field()
    Price_to_Book_MRQ_industry = scrapy.Field()
    Price_to_Tangible_Book_MRQ_industry = scrapy.Field()
    Price_to_Cash_Flow_TTM_industry = scrapy.Field()
    Owned_Institutions_industry = scrapy.Field()

    P_E_Ratio_TTM_sector = scrapy.Field()
    P_E_High_sector = scrapy.Field()
    P_E_Low_sector = scrapy.Field()
    Beta_sector = scrapy.Field()
    Price_to_Sales_TTM_sector = scrapy.Field()
    Price_to_Book_MRQ_sector = scrapy.Field()
    Price_to_Tangible_Book_MRQ_sector = scrapy.Field()
    Price_to_Cash_Flow_TTM_sector = scrapy.Field()
    Owned_Institutions_sector = scrapy.Field()

    Dividend_Yield_Company = scrapy.Field()
    Dividend_Yield_five_Year_Avg_Company = scrapy.Field()
    Dividend_five_Year_Growth_Rate_Company = scrapy.Field()
    Payout_Ratio_TTM_Company = scrapy.Field()

    Dividend_Yield_industry = scrapy.Field()
    Dividend_Yield_five_Year_Avg_industry = scrapy.Field()
    Dividend_five_Year_Growth_Rate_industry = scrapy.Field()
    Payout_Ratio_TTM_industry = scrapy.Field()

    Dividend_Yield_sector = scrapy.Field()
    Dividend_Yield_five_Year_Avg_sector = scrapy.Field()
    Dividend_five_Year_Growth_Rate_sector = scrapy.Field()
    Payout_Ratio_TTM_sector = scrapy.Field()
